# -*- coding: utf-8 -*-
"""Zadanie na sztuczną

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5FYVODDJwXnh6RaOhsb4EM0aoF12U8j
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import VotingClassifier, BaggingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

# ==========================================
# 0. PRZYGOTOWANIE DANYCH
# ==========================================
# Używamy wbudowanego zbioru danych (możesz go zamienić na swój np. pd.read_csv())
data = load_breast_cancer()
X, y = data.data, data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

results = {}

print("--- ROZPOCZĘCIE ANALIZY ---")

# ==========================================
# 1. KROSWALIDACJA I OPTYMALIZACJA PARAMETRÓW
# ==========================================
print("\n[Krok 1] Optymalizacja modeli bazowych...")

# Sieć neuronowa (MLP)
mlp = MLPClassifier(max_iter=500, random_state=42)
param_mlp = {'hidden_layer_sizes': [(10,), (50,), (50, 20)]}
grid_mlp = GridSearchCV(mlp, param_mlp, cv=5, scoring='accuracy').fit(X_train, y_train)
best_mlp = grid_mlp.best_estimator_

# k-Najbliższych Sąsiadów (kNN)
knn = KNeighborsClassifier()
param_knn = {'n_neighbors': [3, 5, 7, 11]}
grid_knn = GridSearchCV(knn, param_knn, cv=5, scoring='accuracy').fit(X_train, y_train)
best_knn = grid_knn.best_estimator_

# Drzewo Decyzyjne (DT)
dt = DecisionTreeClassifier(random_state=42)
param_dt = {'max_depth': [3, 5, 10, None]}
grid_dt = GridSearchCV(dt, param_dt, cv=5, scoring='accuracy').fit(X_train, y_train)
best_dt = grid_dt.best_estimator_

# Zapisywanie wyników modeli bazowych
results['MLP (Optymalny)'] = accuracy_score(y_test, best_mlp.predict(X_test))
results['kNN (Optymalny)'] = accuracy_score(y_test, best_knn.predict(X_test))
results['DT (Optymalny)'] = accuracy_score(y_test, best_dt.predict(X_test))

print(f"Najlepsze parametry NN: {grid_mlp.best_params_}")
print(f"Najlepsze parametry kNN: {grid_knn.best_params_}")
print(f"Najlepsze parametry DT: {grid_dt.best_params_}")

# ==========================================
# 2. KOMITETY (ENSEMBLE METHODS)
# ==========================================
print("\n[Krok 2] Budowanie komitetów...")

# Modele bazowe (domyślne i optymalne) do dalszych kroków
estimators_opt = [('mlp', best_mlp), ('knn', best_knn), ('dt', best_dt)]
estimators_def = [
    ('mlp', MLPClassifier(max_iter=500, random_state=42)),
    ('knn', KNeighborsClassifier()),
    ('dt', DecisionTreeClassifier(random_state=42))
]

# a) Voting (Hard i Soft) na modelach optymalnych
voting_hard = VotingClassifier(estimators=estimators_opt, voting='hard').fit(X_train, y_train)
voting_soft = VotingClassifier(estimators=estimators_opt, voting='soft').fit(X_train, y_train)

results['Voting (Hard)'] = accuracy_score(y_test, voting_hard.predict(X_test))
results['Voting (Soft)'] = accuracy_score(y_test, voting_soft.predict(X_test))

# b) Bagging (Dla modelu domyślnego i optymalnego - używamy Drzewa Decyzyjnego)
bagging_def = BaggingClassifier(estimator=DecisionTreeClassifier(random_state=42), n_estimators=50, random_state=42).fit(X_train, y_train)
bagging_opt = BaggingClassifier(estimator=best_dt, n_estimators=50, random_state=42).fit(X_train, y_train)

results['Bagging (DT Domyślny)'] = accuracy_score(y_test, bagging_def.predict(X_test))
results['Bagging (DT Optymalny)'] = accuracy_score(y_test, bagging_opt.predict(X_test))

# c) Stacking (Te same modele bazowe, sprawdzamy różne modele agregujące/meta-klasyfikatory)
stacking_lr = StackingClassifier(estimators=estimators_opt, final_estimator=LogisticRegression(), cv=5).fit(X_train, y_train)
stacking_dt = StackingClassifier(estimators=estimators_opt, final_estimator=DecisionTreeClassifier(max_depth=3, random_state=42), cv=5).fit(X_train, y_train)

results['Stacking (Meta: Regresja Logistyczna)'] = accuracy_score(y_test, stacking_lr.predict(X_test))
results['Stacking (Meta: Drzewo Decyzyjne)'] = accuracy_score(y_test, stacking_dt.predict(X_test))

# ==========================================
# 3. WYBÓR I KOŃCOWE TRENOWANIE MODELU
# ==========================================
print("\n[Krok 3] Podsumowanie i wybór najlepszego modelu...")

# Prezentacja wyników w formie tabeli
df_results = pd.DataFrame(list(results.items()), columns=['Model / Komitet', 'Dokładność (Accuracy)'])
print("\n", df_results.to_string(index=False))

best_model_name = max(results, key=results.get)
print(f"\n-> Najlepszym modelem okazał się: {best_model_name} z dokładnością {results[best_model_name]:.4f}")